services:
  - type: web
    name: email-outreach-automation
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
    disk:
      name: email-data
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
  
databases:
  - name: email-automation-db
    databaseName: email_automation
    user: email_user
    plan: free

# Note: Environment variables like ANTHROPIC_API_KEY
# will be set through the Render dashboard for security